#!/bin/sh
if [ $# -ne 1 ] ; then
	echo "aucoverage LOG1 | --dump"
	exit 1
fi
INLOG="$1"
if [ "$1" = "--dump" ] ; then
	ausearch -m 2>&1 | tr ' ' '\n'| egrep [A-Z] | egrep -v 'ALL|Argument|Valid|EOE|TRUSTED_APP|KERNEL_OTHER' | sort
	exit 0
fi
if [ ! -e $INLOG ] ; then
	echo "Can't read $INLOG"
	exit 1
fi
types=`ausearch -m 2>&1 | tr ' ' '\n'| egrep [A-Z] | egrep -v 'ALL|Argument|Valid|EOE|TRUSTED_APP|KERNEL_OTHER' | sort`
#echo -e "$types\n\n"
for t in $types
do
	ausearch -if $INLOG -m $t --just-one --raw 2>/dev/null 1>&2
	if [ $? -ne 0 ] ; then
		echo "Missing $t"
	fi
done

